### ISSUE TITLE
Question about "vim-colorscheme"

### ISSUE THREAD

**Issue by EvitanRelta** [shurane/dotfiles#1]
Yoo! :D

I noticed u used my vim colorscheme repo:
https://github.com/EvitanRelta/vim-colorschemes

I was just wondering if u encountered any bugs with it, cuz I didnt test it on other machines/vim-variants

And did it fixed any bug for u, bugs that plagued the original repo by flazz?

This was the only way I could reach out to u lol

**Comment by shurane** [comment]
Wow, never saw this issue. Not really any issues with vim-colorschemes, but it's been a while since I configured it. I mostly just use it as is. I think sometimes the colorschemes aren't up to date? I.e. not having the latest version that fixes color highlighting.
